.TH NX-HARRIS-DETECTOR 1 2019-02-11
.SH NAME
nx-harris-detector \- detects Harris corner points
.SH SYNOPSIS
.B nx-harris-detector
.BR \-i " " \fIfilename\fR 
.RB [ \-\-sigma-int " " \fIintegration-scale\fR ]
.RB [ \-k " " \fIcornerness-score-param\fR ]
.RB [ \-N " " \fImax-n-keys\fR ]
.RB [ \-t " " \fIthreshold\fR ]
.RB [ \-\-key-image " " \fIfilename\fR ]
.RB [ \-v | \-\-verbose ]
.SH DESCRIPTION
\fBnx-harris-detector\fR is a tool for detecting Harris corner points in images.
It prints the detected keypoints to \fIstdout\fR as a JSON object.
It can also output diagnostic information such as an image of keypoint locations.
.SH OPTIONS
.TP
.BR \-i " " \fIfilename\fR
Sets the name of the image file to load.
.TP
.BR \-\-sigma-int " " \fIintegration-scale\fR
Sets the size of the Gaussian window for integrating the auto-corrlation matrix elements.
.TP
.BR \-k " " \fIcornerness-score-param\fR
Sets the value of the parameter \fIk\fR in the Harris cornerness score function.
.TP
.BR \-N " " \fImax-n-keys\fR
Sets the maximum number of keypoints to be detected.
.TP
.BR \-t " " \fIthreshold\fR
Detection threshold for Harris cornerness score.
.TP
.BR \-\-key-image " " \fIfilename\fR
If set, an image with keypoints marked will be saved with the given filename.
.TP
.BR \-v ", " \-\-verbose
Enables more detailed log messages.
These are written to \fIstderr\fR.
