.TH NX-WARP-IMAGE 1 2019-03-20
.SH NAME
nx-warp-image \- applies geometric transforms to image
.SH SYNOPSIS
.B nx-warp-image
.BR \-i " " \fIfilename\fR 
.RB [ \-v | \-\-verbose ]
.SH DESCRIPTION
\fBnx-warp-image\fR is a tool for transformin images geometrically.
It can apply affine deformations to single images.
.SH OPTIONS
.TP
.BR \-i " " \fIfilename\fR
Sets the name of the image file to load.
.TP
.BR \-v ", " \-\-verbose
Enables more detailed log messages.
These are written to \fIstderr\fR.
